# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Pixiv.ui'
#
# Created: Fri Jul 12 22:32:46 2013
#      by: PyQt4 UI code generator 4.10.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWidget(object):
    def setupUi(self, mainWidget):
        mainWidget.setObjectName(_fromUtf8("mainWidget"))
        mainWidget.resize(730, 530)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(mainWidget.sizePolicy().hasHeightForWidth())
        mainWidget.setSizePolicy(sizePolicy)
        mainWidget.setMinimumSize(QtCore.QSize(730, 530))
        mainWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        mainWidget.setStyleSheet(_fromUtf8(""))
        self.gridLayout = QtGui.QGridLayout(mainWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.frame = QtGui.QFrame(mainWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(600, 100))
        self.frame.setStyleSheet(_fromUtf8("QFrame#frame{\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:0.767091, x2:1, y2:0, stop:0 rgba(233,235,239,255), stop:1 rgba(255, 255, 255, 255));\n"
"border-radius:7px;\n"
"}\n"
"\n"
"QToolButton{\n"
"border:None;\n"
"border-radius:7px;\n"
"}\n"
"\n"
"QToolButton:checked,QToolButton:pressed{\n"
"background-color:rgb(133,150,167);\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"background-color:rgb(224,226,230)\n"
"}\n"
"\n"
"QToolButton:checked:hover{\n"
"background-color:rgb(133,150,167);\n"
"}"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.aboutButton = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aboutButton.sizePolicy().hasHeightForWidth())
        self.aboutButton.setSizePolicy(sizePolicy)
        self.aboutButton.setMinimumSize(QtCore.QSize(95, 95))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("simsun"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.aboutButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/orkut-256.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aboutButton.setIcon(icon)
        self.aboutButton.setIconSize(QtCore.QSize(50, 50))
        self.aboutButton.setCheckable(True)
        self.aboutButton.setAutoExclusive(True)
        self.aboutButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.aboutButton.setAutoRaise(False)
        self.aboutButton.setObjectName(_fromUtf8("aboutButton"))
        self.gridLayout_2.addWidget(self.aboutButton, 0, 6, 1, 1)
        self.viewButton = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewButton.sizePolicy().hasHeightForWidth())
        self.viewButton.setSizePolicy(sizePolicy)
        self.viewButton.setMinimumSize(QtCore.QSize(95, 95))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("simsun"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.viewButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/picasa-256.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.viewButton.setIcon(icon1)
        self.viewButton.setIconSize(QtCore.QSize(50, 50))
        self.viewButton.setCheckable(True)
        self.viewButton.setAutoExclusive(True)
        self.viewButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.viewButton.setAutoRaise(False)
        self.viewButton.setObjectName(_fromUtf8("viewButton"))
        self.gridLayout_2.addWidget(self.viewButton, 0, 3, 1, 1)
        self.manageButton = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.manageButton.sizePolicy().hasHeightForWidth())
        self.manageButton.setSizePolicy(sizePolicy)
        self.manageButton.setMinimumSize(QtCore.QSize(95, 95))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("simsun"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.manageButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/foursquare-256.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manageButton.setIcon(icon2)
        self.manageButton.setIconSize(QtCore.QSize(50, 50))
        self.manageButton.setCheckable(True)
        self.manageButton.setAutoExclusive(True)
        self.manageButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.manageButton.setAutoRaise(False)
        self.manageButton.setObjectName(_fromUtf8("manageButton"))
        self.gridLayout_2.addWidget(self.manageButton, 0, 4, 1, 1)
        self.settingButton = QtGui.QToolButton(self.frame)
        self.settingButton.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingButton.sizePolicy().hasHeightForWidth())
        self.settingButton.setSizePolicy(sizePolicy)
        self.settingButton.setMinimumSize(QtCore.QSize(95, 95))
        self.settingButton.setSizeIncrement(QtCore.QSize(0, 0))
        self.settingButton.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("simsun"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.settingButton.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/posterous-256.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.settingButton.setIcon(icon3)
        self.settingButton.setIconSize(QtCore.QSize(50, 50))
        self.settingButton.setCheckable(True)
        self.settingButton.setAutoExclusive(True)
        self.settingButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.settingButton.setAutoRaise(False)
        self.settingButton.setObjectName(_fromUtf8("settingButton"))
        self.gridLayout_2.addWidget(self.settingButton, 0, 5, 1, 1)
        self.downloadButton = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downloadButton.sizePolicy().hasHeightForWidth())
        self.downloadButton.setSizePolicy(sizePolicy)
        self.downloadButton.setMinimumSize(QtCore.QSize(95, 95))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("simsun"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.downloadButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/envato-256.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.downloadButton.setIcon(icon4)
        self.downloadButton.setIconSize(QtCore.QSize(50, 50))
        self.downloadButton.setCheckable(True)
        self.downloadButton.setAutoExclusive(True)
        self.downloadButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.downloadButton.setAutoRaise(False)
        self.downloadButton.setObjectName(_fromUtf8("downloadButton"))
        self.gridLayout_2.addWidget(self.downloadButton, 0, 2, 1, 1)
        self.accountButton = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accountButton.sizePolicy().hasHeightForWidth())
        self.accountButton.setSizePolicy(sizePolicy)
        self.accountButton.setMinimumSize(QtCore.QSize(95, 95))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("simsun"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.accountButton.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/aim-256.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accountButton.setIcon(icon5)
        self.accountButton.setIconSize(QtCore.QSize(50, 50))
        self.accountButton.setCheckable(True)
        self.accountButton.setAutoExclusive(True)
        self.accountButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.accountButton.setAutoRaise(False)
        self.accountButton.setObjectName(_fromUtf8("accountButton"))
        self.gridLayout_2.addWidget(self.accountButton, 0, 1, 1, 1)
        self.loginButton = QtGui.QToolButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.loginButton.sizePolicy().hasHeightForWidth())
        self.loginButton.setSizePolicy(sizePolicy)
        self.loginButton.setMinimumSize(QtCore.QSize(95, 95))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("simsun"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.loginButton.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/icons/icons/gravatar-256.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loginButton.setIcon(icon6)
        self.loginButton.setIconSize(QtCore.QSize(50, 50))
        self.loginButton.setCheckable(True)
        self.loginButton.setAutoExclusive(True)
        self.loginButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.loginButton.setAutoRaise(False)
        self.loginButton.setObjectName(_fromUtf8("loginButton"))
        self.gridLayout_2.addWidget(self.loginButton, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(mainWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setMinimumSize(QtCore.QSize(600, 360))
        self.stackedWidget.setStyleSheet(_fromUtf8("QStackedWidget{\n"
"background-color: rgb(240,241,244);\n"
"\n"
"}\n"
"\n"
"QPushButton{\n"
"background-color: rgb(0,170,248);\n"
"border-radius:5px;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(51, 68, 85);\n"
"}\n"
"\n"
"QLabel{\n"
"border:2px solid rgb(228,228,228);\n"
"border-radius:5px;\n"
"}\n"
"QLineEdit{\n"
"border:2px solid rgb(228,228,228);\n"
"border-radius:5px;\n"
"}"))
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.login = QtGui.QWidget()
        self.login.setObjectName(_fromUtf8("login"))
        self.stackLoginButton = QtGui.QPushButton(self.login)
        self.stackLoginButton.setGeometry(QtCore.QRect(230, 200, 121, 41))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(45)
        sizePolicy.setHeightForWidth(self.stackLoginButton.sizePolicy().hasHeightForWidth())
        self.stackLoginButton.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 170, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        self.stackLoginButton.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.stackLoginButton.setFont(font)
        self.stackLoginButton.setObjectName(_fromUtf8("stackLoginButton"))
        self.layoutWidget = QtGui.QWidget(self.login)
        self.layoutWidget.setGeometry(QtCore.QRect(170, 120, 243, 60))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.stackPassWordLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.stackPassWordLineEdit.setInputMask(_fromUtf8(""))
        self.stackPassWordLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.stackPassWordLineEdit.setObjectName(_fromUtf8("stackPassWordLineEdit"))
        self.gridLayout_6.addWidget(self.stackPassWordLineEdit, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setTextFormat(QtCore.Qt.AutoText)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_6.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.stackPixivIDLineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.stackPixivIDLineEdit.setInputMask(_fromUtf8(""))
        self.stackPixivIDLineEdit.setText(_fromUtf8(""))
        self.stackPixivIDLineEdit.setObjectName(_fromUtf8("stackPixivIDLineEdit"))
        self.gridLayout_6.addWidget(self.stackPixivIDLineEdit, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.login)
        self.page = QtGui.QWidget()
        self.page.setObjectName(_fromUtf8("page"))
        self.stackFollowedUser = QtGui.QPushButton(self.page)
        self.stackFollowedUser.setGeometry(QtCore.QRect(270, 80, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.stackFollowedUser.setFont(font)
        self.stackFollowedUser.setObjectName(_fromUtf8("stackFollowedUser"))
        self.stackAvatar = QtGui.QLabel(self.page)
        self.stackAvatar.setGeometry(QtCore.QRect(40, 60, 170, 170))
        self.stackAvatar.setText(_fromUtf8(""))
        self.stackAvatar.setObjectName(_fromUtf8("stackAvatar"))
        self.stackLogoutButton = QtGui.QPushButton(self.page)
        self.stackLogoutButton.setGeometry(QtCore.QRect(60, 250, 111, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.stackLogoutButton.setFont(font)
        self.stackLogoutButton.setObjectName(_fromUtf8("stackLogoutButton"))
        self.stackedWidget.addWidget(self.page)
        self.download = QtGui.QWidget()
        self.download.setObjectName(_fromUtf8("download"))
        self.label_3 = QtGui.QLabel(self.download)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 81, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setTextFormat(QtCore.Qt.AutoText)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.stackUserID = QtGui.QLineEdit(self.download)
        self.stackUserID.setGeometry(QtCore.QRect(120, 30, 211, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.stackUserID.setFont(font)
        self.stackUserID.setInputMask(_fromUtf8(""))
        self.stackUserID.setText(_fromUtf8(""))
        self.stackUserID.setObjectName(_fromUtf8("stackUserID"))
        self.stackSearchButton = QtGui.QPushButton(self.download)
        self.stackSearchButton.setGeometry(QtCore.QRect(370, 30, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.stackSearchButton.setFont(font)
        self.stackSearchButton.setObjectName(_fromUtf8("stackSearchButton"))
        self.stackedWidget.addWidget(self.download)
        self.page_2 = QtGui.QWidget()
        self.page_2.setObjectName(_fromUtf8("page_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.viewWidget = QtGui.QScrollArea(self.page_2)
        self.viewWidget.setWidgetResizable(True)
        self.viewWidget.setObjectName(_fromUtf8("viewWidget"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 710, 367))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.viewWidget.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_5.addWidget(self.viewWidget, 1, 0, 1, 6)
        self.downloadChecked = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.downloadChecked.setFont(font)
        self.downloadChecked.setObjectName(_fromUtf8("downloadChecked"))
        self.gridLayout_5.addWidget(self.downloadChecked, 0, 5, 1, 1)
        self.pixivUserName = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.pixivUserName.setFont(font)
        self.pixivUserName.setText(_fromUtf8(""))
        self.pixivUserName.setAlignment(QtCore.Qt.AlignCenter)
        self.pixivUserName.setObjectName(_fromUtf8("pixivUserName"))
        self.gridLayout_5.addWidget(self.pixivUserName, 0, 0, 1, 1)
        self.curPage = QtGui.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.curPage.setFont(font)
        self.curPage.setText(_fromUtf8(""))
        self.curPage.setAlignment(QtCore.Qt.AlignCenter)
        self.curPage.setObjectName(_fromUtf8("curPage"))
        self.gridLayout_5.addWidget(self.curPage, 0, 3, 1, 1)
        self.nextPage = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.nextPage.setFont(font)
        self.nextPage.setObjectName(_fromUtf8("nextPage"))
        self.gridLayout_5.addWidget(self.nextPage, 0, 4, 1, 1)
        self.prevPage = QtGui.QPushButton(self.page_2)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.prevPage.setFont(font)
        self.prevPage.setObjectName(_fromUtf8("prevPage"))
        self.gridLayout_5.addWidget(self.prevPage, 0, 2, 1, 1)
        self.stackedWidget.addWidget(self.page_2)
        self.manage = QtGui.QWidget()
        self.manage.setObjectName(_fromUtf8("manage"))
        self.gridLayout_4 = QtGui.QGridLayout(self.manage)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButton = QtGui.QPushButton(self.manage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_4.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.manage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_4.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.manage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_4.addWidget(self.pushButton_7, 0, 2, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.manage)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_4.addWidget(self.pushButton_8, 0, 3, 1, 1)
        self.manageTableWidget = QtGui.QTableWidget(self.manage)
        self.manageTableWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.manageTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.manageTableWidget.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.manageTableWidget.setColumnCount(3)
        self.manageTableWidget.setObjectName(_fromUtf8("manageTableWidget"))
        self.manageTableWidget.setRowCount(0)
        self.manageTableWidget.horizontalHeader().setVisible(False)
        self.manageTableWidget.verticalHeader().setVisible(True)
        self.gridLayout_4.addWidget(self.manageTableWidget, 1, 0, 1, 4)
        self.stackedWidget.addWidget(self.manage)
        self.setting = QtGui.QWidget()
        self.setting.setObjectName(_fromUtf8("setting"))
        self.label_4 = QtGui.QLabel(self.setting)
        self.label_4.setGeometry(QtCore.QRect(30, 30, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setTextFormat(QtCore.Qt.AutoText)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.lineEdit_4 = QtGui.QLineEdit(self.setting)
        self.lineEdit_4.setGeometry(QtCore.QRect(170, 20, 271, 31))
        self.lineEdit_4.setInputMask(_fromUtf8(""))
        self.lineEdit_4.setText(_fromUtf8(""))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.pushButton_3 = QtGui.QPushButton(self.setting)
        self.pushButton_3.setGeometry(QtCore.QRect(470, 20, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.setting)
        self.pushButton_4.setGeometry(QtCore.QRect(140, 290, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.setting)
        self.pushButton_5.setGeometry(QtCore.QRect(280, 290, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(self.setting)
        self.pushButton_6.setGeometry(QtCore.QRect(410, 290, 101, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.label_5 = QtGui.QLabel(self.setting)
        self.label_5.setGeometry(QtCore.QRect(30, 80, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setTextFormat(QtCore.Qt.AutoText)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.comboBox = QtGui.QComboBox(self.setting)
        self.comboBox.setGeometry(QtCore.QRect(170, 80, 69, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.groupBox = QtGui.QGroupBox(self.setting)
        self.groupBox.setGeometry(QtCore.QRect(30, 120, 561, 141))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setTextFormat(QtCore.Qt.AutoText)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lineEdit_5 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_5.setGeometry(QtCore.QRect(140, 10, 271, 31))
        self.lineEdit_5.setInputMask(_fromUtf8(""))
        self.lineEdit_5.setText(_fromUtf8(""))
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.lineEdit_6 = QtGui.QLineEdit(self.groupBox)
        self.lineEdit_6.setGeometry(QtCore.QRect(140, 50, 271, 31))
        self.lineEdit_6.setInputMask(_fromUtf8(""))
        self.lineEdit_6.setText(_fromUtf8(""))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 121, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("宋体"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setTextFormat(QtCore.Qt.AutoText)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.stackedWidget.addWidget(self.setting)
        self.about = QtGui.QWidget()
        self.about.setObjectName(_fromUtf8("about"))
        self.gridLayout_3 = QtGui.QGridLayout(self.about)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.textBrowser = QtGui.QTextBrowser(self.about)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.gridLayout_3.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.about)
        self.gridLayout.addWidget(self.stackedWidget, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 4)

        self.retranslateUi(mainWidget)
        self.stackedWidget.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)
        mainWidget.setTabOrder(self.accountButton, self.downloadButton)
        mainWidget.setTabOrder(self.downloadButton, self.viewButton)
        mainWidget.setTabOrder(self.viewButton, self.manageButton)
        mainWidget.setTabOrder(self.manageButton, self.settingButton)
        mainWidget.setTabOrder(self.settingButton, self.aboutButton)
        mainWidget.setTabOrder(self.aboutButton, self.stackPixivIDLineEdit)
        mainWidget.setTabOrder(self.stackPixivIDLineEdit, self.loginButton)
        mainWidget.setTabOrder(self.loginButton, self.stackPassWordLineEdit)
        mainWidget.setTabOrder(self.stackPassWordLineEdit, self.stackLoginButton)
        mainWidget.setTabOrder(self.stackLoginButton, self.stackFollowedUser)
        mainWidget.setTabOrder(self.stackFollowedUser, self.stackUserID)
        mainWidget.setTabOrder(self.stackUserID, self.stackSearchButton)
        mainWidget.setTabOrder(self.stackSearchButton, self.manageTableWidget)
        mainWidget.setTabOrder(self.manageTableWidget, self.lineEdit_4)
        mainWidget.setTabOrder(self.lineEdit_4, self.pushButton_3)
        mainWidget.setTabOrder(self.pushButton_3, self.pushButton_4)
        mainWidget.setTabOrder(self.pushButton_4, self.pushButton_5)
        mainWidget.setTabOrder(self.pushButton_5, self.pushButton_6)
        mainWidget.setTabOrder(self.pushButton_6, self.comboBox)
        mainWidget.setTabOrder(self.comboBox, self.lineEdit_5)
        mainWidget.setTabOrder(self.lineEdit_5, self.lineEdit_6)
        mainWidget.setTabOrder(self.lineEdit_6, self.textBrowser)
        mainWidget.setTabOrder(self.textBrowser, self.stackLogoutButton)

    def retranslateUi(self, mainWidget):
        mainWidget.setWindowTitle(_translate("mainWidget", "Form", None))
        self.aboutButton.setText(_translate("mainWidget", "关于", None))
        self.viewButton.setText(_translate("mainWidget", "图片浏览", None))
        self.manageButton.setText(_translate("mainWidget", "下载管理", None))
        self.settingButton.setText(_translate("mainWidget", "设置", None))
        self.downloadButton.setText(_translate("mainWidget", "下载", None))
        self.accountButton.setText(_translate("mainWidget", "账户信息", None))
        self.loginButton.setText(_translate("mainWidget", "登陆", None))
        self.stackLoginButton.setText(_translate("mainWidget", "登陆", None))
        self.stackLoginButton.setShortcut(_translate("mainWidget", "Return", None))
        self.label_2.setText(_translate("mainWidget", "密码", None))
        self.label.setText(_translate("mainWidget", "用户名", None))
        self.stackFollowedUser.setText(_translate("mainWidget", "关注用户", None))
        self.stackLogoutButton.setText(_translate("mainWidget", "退出登录", None))
        self.label_3.setText(_translate("mainWidget", "作者ID", None))
        self.stackSearchButton.setText(_translate("mainWidget", "搜索", None))
        self.downloadChecked.setText(_translate("mainWidget", "下载选中", None))
        self.nextPage.setText(_translate("mainWidget", "下一页", None))
        self.prevPage.setText(_translate("mainWidget", "上一页", None))
        self.pushButton.setText(_translate("mainWidget", "开始", None))
        self.pushButton_2.setText(_translate("mainWidget", "停止", None))
        self.pushButton_7.setText(_translate("mainWidget", "全部停止", None))
        self.pushButton_8.setText(_translate("mainWidget", "删除", None))
        self.label_4.setText(_translate("mainWidget", "下载目录", None))
        self.pushButton_3.setText(_translate("mainWidget", "更改", None))
        self.pushButton_4.setText(_translate("mainWidget", "确定", None))
        self.pushButton_5.setText(_translate("mainWidget", "应用", None))
        self.pushButton_6.setText(_translate("mainWidget", "取消", None))
        self.label_5.setText(_translate("mainWidget", "同时下载数量", None))
        self.comboBox.setItemText(0, _translate("mainWidget", "1", None))
        self.comboBox.setItemText(1, _translate("mainWidget", "2", None))
        self.comboBox.setItemText(2, _translate("mainWidget", "4", None))
        self.comboBox.setItemText(3, _translate("mainWidget", "8", None))
        self.comboBox.setItemText(4, _translate("mainWidget", "16", None))
        self.groupBox.setTitle(_translate("mainWidget", "下载过滤", None))
        self.label_6.setText(_translate("mainWidget", "最小评分", None))
        self.label_7.setText(_translate("mainWidget", "排除tag", None))

import pixiv_rc
